name: Sync Issue to Jira issue

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Adding issue in Jira
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: https://www.tegel.atlassian.net
          JIRA_USER_EMAIL: johan.nilo@scania.com
          JIRA_API_TOKEN: TATT3xFfGF0y4orF4KxWVPQZa0wnIUZC7KbjjEVZNfeNhCE4PlHkLO2vvVWa1S__n1NVZgdPjEuRMBEkGzSWpZ4vm6OtpRLcl4uF8T90Gg6tJ3Sug3jnHsbqSn4nsNTrRG67lEUQpk0y5XMrU6__jNbtb13pdtIuEsPwUePTbU0m9eXmrt1gK4=98774614
      - name: Jira Create issue
        uses: atlassian/gajira-create@v3

