name: Sync Issue to Jira issue

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Adding issue in Jira
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: https://https://tegel.atlassian.net/
          JIRA_USER_EMAIL: johan.nilo@scania.com
          JIRA_API_TOKEN: ATATT3xFfGF0AcZD-YlILh7pU1bNFt73CUr0qsXUGyrpKuWv0LBc8_5mtY3mSvI1kVGkEHmtSmJDOGwuNBX-uPY5Qg4V3uT7Uixl01NC9DMyGIqLRs2_FnL6xu5VWVakxHJJ1q_4xd02kOGvfaJI_BldG-0nRDgJe8BAJPM-FNnopRNqSst2b74=62FE8C51
      - name: Jira Create issue
        uses: atlassian/gajira-create@v3

