name: Sync Issue to Jira issue

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Adding issue in Jira
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Jira Create issue
        uses: atlassian/gajira-create@v3

